default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: [pre-commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^chart/templates/
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Lint shell scripts
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
    - id: typos
      name: Check for typos
  - repo: https://github.com/crate-ci/committed
    rev: v1.1.7
    hooks:
    - id: committed
      name: Check commit message formatting
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.11
    hooks:
      - id: ripsecrets
        name: Check no secrets are committed
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: ["--fix"]
        name: Lint and fix Python files
      - id: ruff-format
        name: Format Python files
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Format Rust files
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--"]
      - id: cargo-clippy
        name: Check and lint Rust files (cargo clippy)
        entry: env SQLX_OFFLINE=true cargo clippy
        language: system
        args: ["--all-features", "--all-targets", "--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
